server:
    port: 8080

spring:
    application:
        name: dba-gateway
    cloud:
        config:
            enabled: false
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: dba-professor-id
                  uri: lb://DBA-PROFESSOR
                  predicates:
                      - Path=/api/professors/**
                - id: dba-students-id
                  uri: lb://DBA-STUDENTS
                  predicates:
                      - Path=/api/students/**
                - id: dba-courses-id
                  uri: lb://DBA-COURSES
                  predicates:
                      - Path=/api/courses/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

# spring.application.name=dba-gateway
