server:
  port: 9090

spring:
  application:
    name: dba-professor
  cloud:
    config:
      enabled: false

memcached:
  servers: localhost:11211
  protocol: binary
  operation-timeout: 3000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.unsis.dba_professor: DEBUG
        org.springframework.cache: DEBUG

# spring.application.name=dba-professor
