server:
    port: 8083
spring:
    application:
        name: dba-professor
    config:
        import: optional:configserver:http://localhost:8888

logging:
    level:
        com.unsis.dba_professor: DEBUG
        org.springframework.cache: DEBUG

# spring.application.name=dba-professor
