server:
  port: 9090

spring:
  application:
    name: dba-professor
  cloud:
    config:
      enabled: false

memcached:
  host: ${MEMCACHED_HOST:localhost}
  port: ${MEMCACHED_PORT:11211}
  expiration: 3600

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.unsis.dba_professor: DEBUG
        org.springframework.cache: DEBUG

# spring.application.name=dba-professor
